### ISSUE TITLE
User must sign out twice to sign out

### ISSUE THREAD

**Issue by dtc105** [dtc105/CS-401W#7]
Issue relates to zustand's persist feature, in order for a user to sign out they must hit the sign out button two times.  On the first press the users info flickers off then on and on the second the info is removed as intended.

Branch: backend-authentication

See:
/src/lib/userStore.js
/src/components/User.jsx

**Comment by zcote-ric** [comment]
Added line 120 'navToPage('./');' under onClick in User.jsx to return user to landing page when 'Log Out' button clicked, 'Log In' and 'Register' buttons now display correctly in header after successful log out.

Branch: backend-authentication
